version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
      - ./var/lib/postgresql/data:/var/lib/postgresql/data:rw

  redis:
    image: redis:6.2.6-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION:-3.9.14}-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}

#  varnish:
#    image: varnish:7.1-alpine
#    environment:
#      VARNISH_SIZE: 100M
#    ports:
#      - "8080:80"
##      - "8443:80"
#    tmpfs:
#      - /var/lib/varnish/varnishd:exec
##      - ./var/lib/varnish/varnishd:exec
#    volumes:
#      - ./docker/dev/varnish/default.vcl:/etc/varnish/default.vcl:ro