version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
      - ./var/lib/postgresql/data:/var/lib/postgresql/data:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
#    networks:
#      - backend
###< doctrine/doctrine-bundle ###

#  nginx:
#    image: nginx:1.21.4
#    container_name: nginx
#    environment:
#      - NGINX_HOST=vmeste.dev
#      - NGINX_PORT=80
#    ports:
#      - 80:80
#      - 9000:9000
#    volumes:
#      - ./docker/dev/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./docker/dev/nginx/conf.d/default.nginx:/etc/nginx/conf.d/default.conf:ro
#      - ./:/usr/share/nginx/menu
#      - ./var/cache/nginx:/var/cache/nginx
#      - ./var/log/nginx:/var/log/nginx
#      - /etc/localtime:/etc/localtime:ro
#      - /etc/timezone:/etc/timezone:ro
#    networks:
#      - backend
#    depends_on:
#      - database

#  redis:
#    image: redis:6.2.6-alpine
#    ports:
#      - "6379:6379"

  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION:-3.9.14}-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
#    networks:
#      - backend

#  varnish:
#    image: varnish:7.1-alpine
#    environment:
#      VARNISH_SIZE: 100M
#    ports:
#      - "8080:80"
##      - "8443:80"
#    tmpfs:
#      - /var/lib/varnish/varnishd:exec
##      - ./var/lib/varnish/varnishd:exec
#    volumes:
#      - ./docker/dev/varnish/default.vcl:/etc/varnish/default.vcl:ro

#networks:
#  backend:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 192.168.220.0/28